# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Pascal Brandt
tagline:
description:      'My writing and experiments.'
url:              http://psbrandt.io/

author:
name:             'Pascal Brandt'
url:              https://psbrandt.io/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/psbrandt/psbrandt.github.io
